
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-apiservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-apiservice
  template:
    metadata:
      labels:
        app: demo-apiservice
    spec:
      containers:
      - name: apiservice
        image: 'rynowak/demo-apiservice:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 7443
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-apiservice
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 7443
  selector:
    app: demo-apiservice
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.api.example.com
  namespace: default
spec:
  group: api.example.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: demo-apiservice
    namespace: default
  version: v1alpha1
  insecureSkipTLSVerify: true